version: '2'
services:
  main:
    image: ruby
    command: /bin/bash -c 'cd /usr/src/app; /bin/bash'
    volumes:
      - .:/usr/src/app
    volumes_from:
      - bundle
  bundle:
    # You may need to run `docker-compose build ruby` before this works.
    image: alpine
    command: echo "I'm a little data volume, short and stout"
    volumes:
      - /bundle
